### ISSUE TITLE
Moodle 2.6.2+ - Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; Already seen doctype.

### ISSUE THREAD

**Issue by ghost** [bantonia/MoodleRest#2]
I've tried to connect to a Moodle 2.6.2+ instance but this exception was thrown:

https://gist.github.com/brunoskrebs/10999270

MoodleCallRestWebService.init("http://192.168.0.2/moodle", "a732b2c903bf396cfce678309dd5bec5");

try {
    MoodleCourse[] courses = MoodleRestCourse.getAllCourses();
} catch (Exception e) {
    e.printStackTrace();
}

I am able to connect to Moodle through a web browser with this link:

http://localhost/moodle/webservice/rest/server.php?wstoken=a732b2c903bf396cfce678309dd5bec5&wsfunction=core_course_get_courses

Any ideas what that might be?

Thanks and best regards.

**Comment by bantonia** [comment]
Sorry, it has been some time since I looked at this code. If this is still a problem please open another issue and I will investigate.
