### ISSUE TITLE
MoodleCompletionStatus.java

### ISSUE THREAD

**Issue by sebastianxcf** [bantonia/MoodleRest#3]
public void setField(String nodeName, String content) {
if (nodeName.equals("cmid")) { setCmId(Long.parseLong(content));}
if (nodeName.equals("modname")) {setModName(content);}
**if (nodeName.equals("instance")) { setInstance(Long.parseLong(content));}**
if (nodeName.equals("state")) { setState(Integer.parseInt(content));}
**if (nodeName.equals("timecompleted")) { setInstance(Long.parseLong(content));}**
if (nodeName.equals("tracking")) { setTracking(Long.parseLong(content));}
  }

the value of Instance is being overwrite by the timecompleted value.

**Comment by bantonia** [comment]
Thank you sebastianxcf. I have updated the code, something I haven't looked at for some time.
